# action.yml
name: 'Mimics Scan'
inputs:
  base_url:
    required: true
  api_key:  # id of input
    required: true
  targets:
    required: true
  args:
    required: false
outputs:
  stdout:
    description: "result of mimics command"
runs:
  using: 'docker'
  image: "Dockerfile"
  env:
    MIMICS_BASE_URL: ${{ inputs.BASE_URL }}
    MIMICS_API_KEY: ${{ inputs.API_KEY }}
  args:
    - scan
      ${{ inputs.targets }}
      -c 'Storage Container Without Server Side Encryption Enabled'
      -s 'Github Actions Demo'
      --report-formats all
      --no-progress
