# action.yml
name: 'Mimics Scan'
inputs:
  api_key:  # id of input
    required: true
  args:
    required: false
outputs:
  stdout:
    description: "result of mimics command"
runs:
  using: 'docker'
  image: "Dockerfile"
