# action.yml
name: 'Mimics Scan'
inputs:
  api_key:  # id of input
    required: true
outputs:
  stdout: # id of output
    value: "I am an output!"
    description: 'stdout of mimics'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api_key }}
