name: Rapid7 mimICS Scan
author: Yvonne Kim
description: >
  Scans files with mimICS and saves results to disk.
inputs:
  base_url:
    description: URL of ICS server
    required: true
  api_key:
    description: Api key for server at base_url
    required: true
  args:
    description: Files to scan
    required: true
  config_name:
    description: Name of configuration to run scan with
    required: true
  scan_name:
    description: Name of this scan run
    required: true
outputs:
  stdout:
    description: "Result of mimICS command"
runs:
  using: 'docker'
  image: "docker://mimicsdemo.azurecr.io/mimics:demo"
  env:
    MIMICS_BASE_URL: ${{ inputs.BASE_URL }}
    MIMICS_API_KEY: ${{ inputs.API_KEY }}
  args:
    - scan
    - ${{ inputs.targets }}
    - -c
    - ${{ inputs.config_name }}
    - -s
    - ${{ inputs.scan_name }}
    - --report-formats
    - all
    - --no-progress
