# action.yml
name: 'Mimics Scan'
inputs:
  api-key:  # id of input
    required: true
outputs:
  stdout: # id of output
  description: 'stdout of mimics'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api-key }}
