# action.yml
name: 'Mimics Scan'
inputs:
  api-key:  # id of input
    required: true
outputs:
  stdout: # id of output
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api-key }}
