# action.yml
name: 'Mimics Scan'
inputs:
  base_url:
    required: true
  api_key:  # id of input
    required: true
  args:
    required: false
outputs:
  stdout:
    description: "result of mimics command"
runs:
  using: 'docker'
  image: "Dockerfile"
  args:
    - --api-key ${{ inputs.api_key }}
    - --base-url ${{ inputs.base_url }}
    - scan
    - example.yml
    - -c "Storage Container Without Server Side Encryption Enabled"
    - -s "Github Actions Demo"
    - --report-formats all
    - --no-progress
