# action.yml
name: 'Mimics Scan'
inputs:
  base_url:
    required: true
  api_key:  # id of input
    required: true
  args:
    required: false
outputs:
  stdout:
    description: "result of mimics command"
runs:
  using: 'docker'
  image: "Dockerfile"
  env:
    MIMICS_BASE_URL: ${{ secrets.BASE_URL }}
    MIMICS_API_KEY: ${{ secrets.API_KEY }}
  args:
    - scan
      example.yml
      -c "Storage Container Without Server Side Encryption Enabled"
      -s "Github Actions Demo"
      --report-formats all
      --no-progress
