AWSTemplateFormatVersion: 2010-09-09

Resources:
  BucketAboutIt:
    Type: AWS::S3::Bucket

Outputs:
  
  Block1:
    Value: !Select 
        - 0
        - Fn::Cidr: 
          - 11.0.0.0/16
          - 3
          - 8

  Block2:
    Value: !Select 
        - 1
        - Fn::Cidr: 
          - 12.0.0.0/16
          - 3
          - 8
