on:
  workflow_call:
    inputs:
      commit:
        required: true
    secrets: inherit
    outputs:
      changed-files: ${{ jobs.get-changed-files.outputs.changed-files}}

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ fromJson(steps.call-api.outputs.data).files.*.filename }}
    steps:
      - id: call-api
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/commits/${{ inputs.commit }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  scan:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/scan.yml
      with:
        targets: ${{ jobs.get-changed-files.outputs.targets }}

