on:
  push:
    branches:
      - main

jobs:
  mimics_scan_job:
    runs-on: ubuntu-latest
    name: A job to scan with mimics
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: mimics step
        env:
        uses: ykim-r7/test-action@main
        id: mimics
        with:
          api_key: ${{ secrets.api_key }}
          base_url: ${{ secrets.base_url }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: example.sarif
