on:
  push:
    branches:
      - main

jobs:
  get-targets:
    outputs:
      all_changed_files: ${{ steps.split.outputs }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - id: changed-files
        uses: tj-actions/changed-files@v19

      - id: split
        uses: JungWinter/split@v2.0.0
        with:
          msg: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs }}; do
            echo "$file was changed"
          done

  mimcs-scan:
    name: Scan and Upload
    needs: get-targets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ needs.get-targets.outputs.all_changed_and_modified_files }}
    steps:
      - uses: actions/checkout@v3
      - name: Run mimICS
        uses: ykim-r7/test-action@main
        id: mimics
        with:
          api_key: ${{ secrets.api_key }}
          base_url: ${{ secrets.base_url }}
          target: ${{ matrix.target }}
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: example.sarif
