on:
  push:
    branches:
      - main

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    name: Collect Changed Files
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJson(github.event.commits.*.id) }}
        run: |
          echo $EVENT_CONTEXT

  mimcs-scan:
    needs: get-changed-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commit_id: ${{ github.event.commits.*.id }}
    
    name: Scan and Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: octokit/request-action@v2.x
        id: get_commit
        with:
          route: GET /repos/${{ github.repository }}/commits/${{ matrix.commit_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - env:
          COMMIT_OUTPUTS: ${{ steps.get_commit.outputs.data.files }}
        run: |
          echo $COMMIT_OUTPUTS

      - name: Run mimICS
        uses: ykim-r7/test-action@main
        id: mimics
        with:
          api_key: ${{ secrets.api_key }}
          base_url: ${{ secrets.base_url }}
          target: ${{ steps.get_commit.outputs.data.files[0].filename }}

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: example.sarif
