on:
  push:
    branches:
      - main

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    name: Collect Changed Files
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJson(github.event.commits.*.id) }}
        run: |
          echo $EVENT_CONTEXT
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::"$EVENT_CONTEXT
      - name: debugg
        run: echo ${{ steps.set-matrix.outputs.matrix }}

  mimcs-scan:
    needs: get-changed-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.get-changed-files.outputs.matrix) }}
    
    name: Scan and Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run mimICS
        uses: ykim-r7/test-action@main
        id: mimics
        with:
          api_key: ${{ secrets.api_key }}
          base_url: ${{ secrets.base_url }}
          target: $${{join(github.event.commits.*.id, ' ')}}

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: example.sarif
