on:
  push:
    branches:
      - main

jobs:
  mimics_scan_job:
    runs-on: ubuntu-latest
    name: A job to scan with mimics
    env:
      MIMICS: public.ecr.aws/divvycloud/mimics:latest

    steps:
      - name: mimics step
        env:
          ICS_BASE_URL: https://sales-demo.divvycloud.com/

        uses: ykim-r7/test-action@v4
        id: mimics
        with:
          api_key: ${{ secrets.api_key }}
          entrypoint: /entrypoint.sh
          args: --help

      - name: Archive Scan Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scan-results
          path: reports/
