on:
  push:
    branches:
      - main

jobs:
  mimics_scan_job:
    runs-on: ubuntu-latest
    name: A job to scan with mimics
    steps:
      - name: mimics step
        uses: ykim-r7/test-action@latest
        id: mimics
        with:
          api_key: ${{ secrets.api_key }}
      - name: debug
        run: echo $INPUT_API_KEY; echo $INPUT_API-KEY
