on:
  push:
    branches:
      - main

jobs:
  mimics_scan_job:
    runs-on: ubuntu-latest
    name: A job to scan with mimics
    steps:
      - name: mimics step
        uses: ykim-r7/test-action@latest
        id: mimics
        with:
          api-key: ${{ secrets.api_key }}
      - name: Get the output 
        run: echo ${{ steps.mimics.outputs.stdout }}
