on:
  push:
    branches:
      - main

jobs:
  mimics_scan_job:
    runs-on: ubuntu-latest
    name: A job to scan with mimics
    steps:
      - name: mimics step
        env:
          ICS_BASE_URL: https://sales-demo.divvycloud.com/

        uses: ykim-r7/test-action@main
        id: mimics
        with:
          api_key: ${{ secrets.api_key }}

