on:
  push:
    branches:
      - main

jobs:
  scan:
    strategy:
      matrix:
        commit: ${{ github.event.commits.*.id }}
    uses: ./.github/workflows/changed-files.yml
    with:
      commit: ${{ matrix.commit }}
