on:
  workflow_call:
    inputs:
      targets:
        required: true
    secrets: inherit

jobs:
  mimcs-scan:
    name: Scan and Upload
    runs-on: ubuntu-latest
    strategy:
      target: ${{ inputs.targets }}
    steps:
      - uses: actions/checkout@v3
      - name: Run mimICS
        uses: ykim-r7/test-action@main
        id: mimics
        with:
          api_key: ${{ secrets.api_key }}
          base_url: ${{ secrets.base_url }}
          target: ${{ matrix.target }}
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: example.sarif
